var myMap = new Map();
myMap.set("fname", "sam");
myMap.set("age", 30);
console.log(myMap.get("fname"));
var ob1 = {};
var ob2 = {};
myMap.set(ob1, 10);
mySet.set(ob2, 20);
console.log(myMap(ob1));
console.log(myMap.size);
